name: Web Automation Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
  
    steps:
    #download repo
    - uses: actions/checkout@v3

    #setup java
    - name: Set up JDK 18
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: 'temurin'
    #install browser
    - name: Setup Edge
      uses: browser-actions/setup-edge@v1.1.0
   #setup gradlew
    - name: Setup Gradlew
      run: chmod +x gradlew
    #Execute gradle command for running cucumber test
    - name: Execute Test
      run: ./gradlew cucumber
